package com.artech.prototype2.saver.bardakov.entity.impl;
// Generated 08.12.2014 17:02:32 by Hibernate Tools 3.6.0



/**
 * IndexedWeb generated by hbm2java
 */
public class IndexedWeb  implements java.io.Serializable {


     private Integer id;
     private String urlT;
     private String urlO;
     private String textRu;
     private String textEn;

    public IndexedWeb() {
    }

    public IndexedWeb(String urlT, String urlO, String textRu, String textEn) {
       this.urlT = urlT;
       this.urlO = urlO;
       this.textRu = textRu;
       this.textEn = textEn;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUrlT() {
        return this.urlT;
    }
    
    public void setUrlT(String urlT) {
        this.urlT = urlT;
    }
    public String getUrlO() {
        return this.urlO;
    }
    
    public void setUrlO(String urlO) {
        this.urlO = urlO;
    }
    public String getTextRu() {
        return this.textRu;
    }
    
    public void setTextRu(String textRu) {
        this.textRu = textRu;
    }
    public String getTextEn() {
        return this.textEn;
    }
    
    public void setTextEn(String textEn) {
        this.textEn = textEn;
    }




}


