CREATE TABLE IF NOT EXISTS INDEXED_WEB
(
    ID INT(20) NOT NULL AUTO_INCREMENT,
    URL_T TEXT NOT NULL,
    URL_O TEXT NOT NULL,
    TEXT_RU TEXT CHARACTER SET utf8 NOT NULL,
    TEXT_EN TEXT CHARACTER SET utf8 NOT NULL,
    PRIMARY KEY(ID)
);
